### ISSUE TITLE
GitHub Actions を設定する

### ISSUE THREAD

**Issue by matsuo0227** [nomlab/jay#93]
Created from [AI0771](http://jay.swlab.cs.okayama-u.ac.jp/minutes/1144?ai=0771) of minute 1144.
+ jay の GitHub Actions を設定する -->(中園，中川，田井 !:0771)

**Comment by nakazono0424** [comment]
2021/5/27 第2回開発打合せ時点での進捗

+ swimmy を参考に `ruby.yml` を作成した．
+ 5/27時点での ubuntu-latest (ubuntu-20.04) では Ruby 3.0.1 がサポートされていなかったため，Ruby 3.0.0 で設定した．
+ テストを実行するために新しく RSpec の gem を追加した．
+ 簡単なテストを `jay_spec.rb` に記述した．
+ fork したリモートリポジトリで別ブランチから PR を送ってみると Github Actions が正常に動作していることを確認した．

**Comment by nakazono0424** [comment]
第2回開発打合せ 議論内容

+ テストは rspec ではなく，Rails に標準で備わっている minitest を用いて行う．
+ 現時点では Dockerfile と独立した存在になっているため，Dockerfile を用いてテストを行う Github Actions にする．

**Comment by nakazono0424** [comment]
# minitest を用いてテストを行う
まずローカルリポジトリで`bundle exec rails test`を実行すると，以下のメッセージが表示された．
```
Migrations are pending. To resolve this issue, run:

        bin/rails db:migrate RAILS_ENV=test
```

このため，メッセージ通りに`bundle exec rails db:migrate RAILS_ENV=test`を実行．
以下のメッセージが表示された．
```
rails aborted!
StandardError: An error has occurred, this and all later migrations canceled:

Directly inheriting from ActiveRecord::Migration is not supported. Please specify the Rails release the migration was written for:

  class CreateUsers < ActiveRecord::Migration[4.2]
/home/<User>/workspace/jay/db/migrate/20150609083528_create_users.rb:1:in `<top (required)>'

Caused by:
StandardError: Directly inheriting from ActiveRecord::Migration is not supported. Please specify the Rails release the migration was written for:

  class CreateUsers < ActiveRecord::Migration[4.2]
/home/<User>/workspace/jay/db/migrate/20150609083528_create_users.rb:1:in `<top (required)>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
```
[Rails ガイド](https://railsguides.jp/upgrading_ruby_on_rails.html#active-record-%E3%83%A2%E3%83%87%E3%83%AB%E3%81%AF%E4%BB%8A%E5%BE%8C%E3%83%87%E3%83%95%E3%82%A9%E3%83%AB%E3%83%88%E3%81%A7-applicationrecord-%E3%82%92%E7%B6%99%E6%89%BF%E3%81%99%E3%82%8B)によると，Rails 4.2 の ActiveRecord モデルは`ActiveRecord::Base` を継承していたが，Rails 5.0 以降では`ApplicationRecord` を継承するようになったと記載されている．
また，すべてのモデルが`ApplicationRecord`を継承するように変更して動作を確認するようにという記述もあったため，これが原因だと考えられる．

**Comment by nakazono0424** [comment]
「モデルが ApplicationRecord を継承するように変更する」を #99 として新しく Issue を作成

**Comment by nakazono0424** [comment]
+ ApplicationRecord を継承するだけでは`bundle exec rails db:migrate` で失敗し，以下のようにRails のバージョンを指定したら成功した．もっとちゃんとエラーメッセージを読めばよかった．
`class CreateUsers < ActiveRecord::Migration[4.2]`

+ `bundle exec rails test` を行うとテストはすべて失敗した．自動生成されるテスト項目は，ログイン状態を考慮していないことが原因だと思われる．

+ Github Actions で minitest を実行することが目的のため，とりあえずテスト項目をすべて削除し，ログインしていなくてもアクセスできるルートパス `/` に GET リクエストを送るテストだけ設定した．
